### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by tonyliang19** [rehan13/dsci-310-group-08-AKRM#26]
# Milestone 2 Feedback Group 8

### Code is abstracted to functions with good function design 

- [x] Repeated code of spec, recipe and workflow that could be abstracted to function **-5**

### Helper data for tests is tractable and reproducible

- [x] Repeated helper data that could be store or saved as function/csv as well for reproducibility **-2**

#### Tests suite is of high quality

- [x] Tests are of poor quality, all over the places instead of testing by functionality or component of the function, not robust enought, no input validation **-8**

### Dependecies Update

- [x] Missed `kknn` **-1**

### Project file and directory struture organization

- [x] Extra `*.ipynb`, please only keep it if you decide to use that as your analysis basis and provide corresponding instruction to run it **-1**

#### Follows GitHub flow version control workflow
- [x] Do not merge PRs by yourself, let your teammate `review and approve` (actual functionality on GitHub) and then they merge it for you **-1**

### Analysis can be run reproducibly using doc in README

- [x] Limit option to build the image (this could take very long if large) instead of pulling from DockerHub **-2**
- [x] Failed to reproduce analysis **-10**
