### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by tonyliang19** [rehan13/dsci-310-group-08-AKRM#3]
Please read below feedbacks on things that you could've improve on for future milestones, **NOTE** if these are not fixed, marks will be deducted. If you have any questions on these feedbacks, please feel free to drop-in to my office hour or during lecture time

# Milestone 1 Feedback Group 8

### README.md

- [x] The summary is too vague, it should still provide an overview on the project you did (methods of how? data source?) **-1**

- [x] Did not pin the versions and names of dependencies of the project **-1**

- [x] Did not add detailed instruction for run, your solution might not work for all OS systems: Windows/Mac/Linux, fyi Windows failed, and consider providing `git clone` and `cd` instructions **-1**

- [x] Please be clear on the names of Licenses you hold for the project, you mentioned CC 4.0, while LICENSE.md constains both MIT and CC 4.0 **-1** 

### Dockerfile

Please do not blindly copy other people's Dockerfile's content, use `FROM <base_image>:<version>` instead if you re trying to make your project image based on that `base_image`

- [x] Including non-neccesary packages like in `Julia` **-2**

### Project File and Directory Structure

- [x] Extra `.ipynb.checkpoints` under `data/` **-1**

#### Workflow

- [x] Only triggers when pushed to **Dockerfile**, and not on any changes made on the main **-1**

#### Project/Milestones/Issues

- [x] No GitHub Milestone **-4**
- [x] No GitHub Project **-5**

#### Flow Version Control

- [x] Poor use of PRs **-5**

#### Release

- [x] Poor use of tag, named `latest` instead of `0.0.1`**-1**

### Reproducibility

- [x] Failed to reproduce analysis using instructions provided in README.md **-10**
