### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by tonyliang19** [rehan13/dsci-310-group-08-AKRM#55]
# Milestone 3 Feedback Group 8

## Dependencies have been updated (so it include test libraries)

- [x] Did not include `testthat` for libraries **-1**
- [x] Version mismatch in `ggplot2`, `rmarkdown`. `Docopt` and `bookdown` has extra `.`, package name should be explicity **-1**

Side note:

The version mismatch would be a **-2** instead, but only 2 points can be deducted here.

![image](https://user-images.githubusercontent.com/83138402/230211326-7b80a9d2-da66-483b-8787-b67813ff00bb.png)

## Project file and directory structure organization

- [ ] Too many `csvs` and `pngs` inside same directory of `Results`, this could even divide further to `Results/figures` ... or Results/`output_frames` **-1**

## Analysis can be run reproducibly using documentation provided in README

- [x] Fails to reproduce using instructions **-8**

## Address Feedback from Milestone 1 and 2

Up to 50 % of Milestone 1 + Milestone 2 points, if feedback and comments are adequately addressed

### [Milestone 2 Feedback](https://github.com/rehan13/dsci-310-group-08-AKRM/issues/26)

-  Code is abstracted to functions with good function design **50% of 5 = 2.5**
- Helper data for tests is tractable and reproducible **50% of 2 = 1**
- Tests suite is of high quality **50% of 8 = 4**
- Dependecies Update **50% of 1 = 0.5**
- Project File and Directory Structure **50% of 1 = 0.5**
- GitHub Flow Version Control **50% of 1 = 0.5**
- Analysis can be run reproducibly using doc in README
    + Limit option to build the image (this could take very long if large) instead of pulling from DockerHub **50% of 2 = 1**

Total = $2.5 + 1 + 4 + (0.5 * 3 )+ 1 = 10$ points

### [Milestone 1 Feedback](https://github.com/rehan13/dsci-310-group-08-AKRM/issues/3)

- `README.md` **50% of 4 = 2**
- Dockerfile **50% of 2 = 1**
- Project File and Directory Structure **50% of 1 = 0.5**
- GitHub Workflow **50% of 1 = 0.5**
- GitHub Project/Milestones/Issues **50% of 9 = 4.5**
- GitHub Flow Version Control **50% of 5 = 2.5**
- Release **50% of 1 = 0.5** 

Total = $2 + 1 + (0.5*3) + 4.5 + 2.5 = 11.5$ points
